package ce.pens.entity

import kotlinx.serialization.Serializable

@Serializable
data class TrainFeature(
    val dstPort: Int,
    val protocol: Int,
    val flowDuration: Long,
    val fwdPktCount: Long,
    val bwdPktCount: Long,
    val fwdPktStats: Double,
    val bwdPktStats: Double,
    val fwdPktMax: Double,
    val fwdPktMin: Double,
    val fwdPktMean: Double,
    val fwdPktStd: Double,
    val bwdPktMax: Double,
    val bwdPktMin: Double,
    val bwdPktMean: Double,
    val bwdPktStd: Double,
    val flowBytePs: Double,
    val flowPktPs: Double,
    val flowIATMean: Double,
    val flowIATStd: Double,
    val flowIATMax: Double,
    val flowIATMin: Double,
    val fwdIATSum: Double,
    val fwdIATMean: Double,
    val fwdIATStd: Double,
    val fwdIATMax: Double,
    val fwdIATMin: Double,
    val bwdIATSum: Double,
    val bwdIATMean: Double,
    val bwdIATStd: Double,
    val bwdIATMax: Double,
    val bwdIATMin: Double,
    val fwdPshCount: Int,
    val fwdHeaderLen: Double,
    val bwdHeaderLen: Double,
    val fwdPktPS: Double,
    val bwdPktPS: Double,
    val PktLenMin: Double,
    val PktLenMax: Double,
    val pktLenMean: Double,
    val pktLenStd: Double,
    val pktLenvar: Double,
    val finFlagCnt: Int,
    val synFlagCnt: Int,
    val rstFlagCnt: Int,
    val pshFlagCnt: Int,
    val ackFlagCnt: Int,
    val urgFlagCnt: Int,
    val eceFlagCnt: Int,
    val avgPktSize: Double,
    val fwdAvgSegmentSize: Double,
    val bwdAvgSegmentSize: Double,
    val fwdSubFlowPkt: Long,
    val fwdSubFlowBytes: Long,
    val bwdSubFlowPkt: Long,
    val bwdSubFlowBytes: Long,
    val initWinBytesFwd: Int,
    val initWinBytesBwd: Int,
    val fwdActData: Long,
    val fwdSegSize: Long,
    val flowActiveMean: Double,
    val flowActiveStd: Double,
    val flowActiveMax: Double,
    val flowActiveMin: Double,
    val flowIdleMean: Double,
    val flowIdleStd: Double,
    val flowIdleMax: Double,
    val flowIdleMin: Double,
)

//{'Bwd Blk Rate Avg -v',
//    'Bwd Byts/b Avg -v',
//    'Bwd PSH Flags -v',
//    'Bwd Pkts/b Avg -v',
//    'Bwd URG Flags' -v,
//    'CWE Flag Count' -v,
//    'Fwd Blk Rate Avg' -v,
//    'Fwd Byts/b Avg' -v,
//    'Fwd Pkts/b Avg -v',
//    'Fwd URG Flags' -v}